version: '2'
services:
  grafana_graphite:
    build: .
    image: kamon/grafana_graphite
    container_name: kamon-grafana-dashboard
    ports:
      - '${PORT}:80'
      - '8081:81'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
